/* Generated By:JavaCC: Do not edit this line. GMLParserConstants.java */
package org.arakhne.neteditor.io.gml.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
interface GMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int DECIMAL_PART = 8;
  /** RegularExpression Id. */
  int EXPONENTIAL_PART = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int STRING_ELEMENT = 11;
  /** RegularExpression Id. */
  int KEY = 12;
  /** RegularExpression Id. */
  int LETTER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<NUMBER>",
    "<DIGIT>",
    "<DECIMAL_PART>",
    "<EXPONENTIAL_PART>",
    "<STRING>",
    "<STRING_ELEMENT>",
    "<KEY>",
    "<LETTER>",
    "\"[\"",
    "\"]\"",
  };

}
